apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-ingestion
  namespace: call-center
spec:
  replicas: 2
  selector:
    matchLabels:
      app: call-ingestion
  template:
    metadata:
      labels:
        app: call-ingestion
    spec:
      containers:
        - name: call-ingestion
          image: call-ingestion:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: call-center-config
            - secretRef:
                name: call-center-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
