apiVersion: v1
kind: ConfigMap
metadata:
  name: call-center-config
  namespace: call-center
data:
  ROCKETMQ_NAME_SERVER: rocketmq-nameserver:9876
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USER: call
  ES_URI: http://elasticsearch:9200
  ES_USERNAME: elastic
  REDIS_HOST: redis
