CREATE TABLE IF NOT EXISTS call_dead_letter_task (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    task_key VARCHAR(255) NOT NULL,
    message_type VARCHAR(32) NOT NULL,
    source_topic VARCHAR(128) NOT NULL,
    source_partition INT NOT NULL,
    source_offset BIGINT NOT NULL,
    dlq_topic VARCHAR(128) NOT NULL,
    dlq_queue_offset BIGINT NOT NULL,
    origin_message_id VARCHAR(128) NULL,
    message_key VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    payload_type VARCHAR(32) NOT NULL,
    payload JSON NOT NULL,
    status VARCHAR(16) NOT NULL,
    dlq_attempt INT NOT NULL,
    dlq_max_attempts INT NOT NULL,
    first_failure_at DATETIME NULL,
    last_failure_at DATETIME NOT NULL,
    error_class VARCHAR(255) NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_call_dead_letter_task_task_key (task_key),
    KEY idx_call_dead_letter_task_status_created (status, created_at, id),
    KEY idx_call_dead_letter_task_message_type (message_type, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
